version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8009:80
    environment:
      - DATABASE_URL=postgresql://fastapi_test:fastapi_test@db:5432/fastapi_test
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=fastapi_test
      - POSTGRES_PASSWORD=fastapi_test
      - POSTGRES_DB=fastapi_test

volumes:
  postgres_data:
